name: "Setup AWS and ECR Login"
description: "Configures AWS credentials and logs into Amazon ECR"

inputs:
  aws-region:
    description: "AWS Region"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set AWS Credentials
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}" >> $GITHUB_ENV
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2